### ISSUE TITLE
Spelling Mistake in Documentation

### ISSUE THREAD

**Issue by sbalan7** [lpsinger/ligo.skymap#10]
In the documentation for localizing simulated events with BAYESTAR, there is a typo in the first section (Draw Injections) where it is advised to use `lalapps_inpsinj --help`. This throws a command not found error. It can be fixed by replacing the command with `lalapps_inspinj -- help`. I believe changing the spelling to the right one should fix the issue. The link to the page can be found [here](https://lscsoft.docs.ligo.org/ligo.skymap/quickstart/bayestar-injections.html).

**Comment by lpsinger** [comment]
Thanks! Fixed.
