### ISSUE TITLE
ERROR: Failed building wheel for numpy

### ISSUE THREAD

**Issue by scimaksim** [lpsinger/ligo.skymap#13]
Dependency on numpy 1.19.3 is preventing installation (ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects), could the pyproject.toml be updated with a more recent version of numpy?

**Comment by lpsinger** [comment]
We generally build wheels against the oldest version of Numpy that is supported by Scipy through the [oldest-supported-numpy](https://github.com/scipy/oldest-supported-numpy) metapackage. Some time ago we had to pin it to what was then a slightly newer version (1.19.3). I'm now trying reverting to oldest-supported-numpy in https://git.ligo.org/lscsoft/ligo.skymap/-/merge_requests/274.

What platform and CPU architecture are you on?

**Comment by lpsinger** [comment]
Yes, lalsuite is a complicated package that is not yet being built for aarch64.
