### ISSUE TITLE
center argument for all projects

### ISSUE THREAD

**Issue by grburgess** [lpsinger/ligo.skymap#14]
Is it possible to add a center argument for all the projections? I'm will to make a PR if you can point me to the correct place to implement this.

**Comment by lpsinger** [comment]
It's a great idea!

You can just fork this repo and submit a PR through GitHub.

(The official repo is at https://git.ligo.org/lscsoft/ligo.skymap, but you need a git.ligo.org account to submit a merge request there, and you probably don't have one. So once the PR is ready, I can scoop up the patch from your GitHub PR and manually push it.)
