### ISSUE TITLE
Wheel error during ligo.skymap installation

### ISSUE THREAD

**Issue by juliagrotova** [lpsinger/ligo.skymap#15]
Hello! I'm trying to install ligo.skymap with pip, however, I get errors on the stage of building wheels for collected packages: ligo-segments, python-ligo-lw, lscsoft-glue. I tried the solutions described in similar situations, but it didn't work.
Could you please help me to solve it?

Here is my Terminal output (sorry if it's too long):

> Building wheels for collected packages: ligo-segments, python-ligo-lw, lscsoft-glue
>   Building wheel for ligo-segments (setup.py) ... error
>   error: subprocess-exited-with-error
>  × python setup.py bdist_wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [19 lines of output]
>       /usr/local/lib/python3.8/site-packages/setuptools/dist.py:286: SetuptoolsDeprecationWarning: The namespace_packages parameter is deprecated, consider using implicit namespaces instead (PEP 420).
>         warnings.warn(msg, SetuptoolsDeprecationWarning)
>       running bdist_wheel
>       running build
>       running build_py
>       creating build
>       creating build/lib.macosx-10.15-x86_64-cpython-38
>       creating build/lib.macosx-10.15-x86_64-cpython-38/ligo
>       copying ligo/__init__.py -> build/lib.macosx-10.15-x86_64-cpython-38/ligo
>       creating build/lib.macosx-10.15-x86_64-cpython-38/ligo/segments
>       copying ligo/segments/__init__.py -> build/lib.macosx-10.15-x86_64-cpython-38/ligo/segments
>       copying ligo/segments/utils.py -> build/lib.macosx-10.15-x86_64-cpython-38/ligo/segments
>       running build_ext
>       building 'ligo.segments.__segments' extension
>       creating build/temp.macosx-10.15-x86_64-cpython-38
>       creating build/temp.macosx-10.15-x86_64-cpython-38/src
>       clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -Isrc -I/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/include/python3.8 -c src/infinity.c -o build/temp.macosx-10.15-x86_64-cpython-38/src/infinity.o
>       xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
>       error: command '/usr/bin/clang' failed with exit code 1
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for ligo-segments
>   Running setup.py clean for ligo-segments
>   Building wheel for python-ligo-lw (setup.py) ... error
>   error: subprocess-exited-with-error
>   
>   × python setup.py bdist_wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [36 lines of output]
>       /usr/local/lib/python3.8/site-packages/setuptools/dist.py:286: SetuptoolsDeprecationWarning: The namespace_packages parameter is deprecated, consider using implicit namespaces instead (PEP 420).
>         warnings.warn(msg, SetuptoolsDeprecationWarning)
>       running bdist_wheel
>       running build
>       running build_py
>       creating build
>       creating build/lib.macosx-10.15-x86_64-cpython-38
>       creating build/lib.macosx-10.15-x86_64-cpython-38/ligo
>       copying ligo/__init__.py -> build/lib.macosx-10.15-x86_64-cpython-38/ligo
>       creating build/lib.macosx-10.15-x86_64-cpython-38/ligo/lw
>       copying ligo/lw/ligolw.py -> build/lib.macosx-10.15-x86_64-cpython-38/ligo/lw
>       copying ligo/lw/lsctables.py -> build/lib.macosx-10.15-x86_64-cpython-38/ligo/lw
>       copying ligo/lw/__init__.py -> build/lib.macosx-10.15-x86_64-cpython-38/ligo/lw
>       copying ligo/lw/param.py -> build/lib.macosx-10.15-x86_64-cpython-38/ligo/lw
>       copying ligo/lw/types.py -> build/lib.macosx-10.15-x86_64-cpython-38/ligo/lw
>       copying ligo/lw/dbtables.py -> build/lib.macosx-10.15-x86_64-cpython-38/ligo/lw
>       copying ligo/lw/table.py -> build/lib.macosx-10.15-x86_64-cpython-38/ligo/lw
>       copying ligo/lw/array.py -> build/lib.macosx-10.15-x86_64-cpython-38/ligo/lw
>       creating build/lib.macosx-10.15-x86_64-cpython-38/ligo/lw/utils
>       copying ligo/lw/utils/ligolw_add.py -> build/lib.macosx-10.15-x86_64-cpython-38/ligo/lw/utils
>       copying ligo/lw/utils/search_summary.py -> build/lib.macosx-10.15-x86_64-cpython-38/ligo/lw/utils
>       copying ligo/lw/utils/ilwd.py -> build/lib.macosx-10.15-x86_64-cpython-38/ligo/lw/utils
>       copying ligo/lw/utils/segments.py -> build/lib.macosx-10.15-x86_64-cpython-38/ligo/lw/utils
>       copying ligo/lw/utils/__init__.py -> build/lib.macosx-10.15-x86_64-cpython-38/ligo/lw/utils
>       copying ligo/lw/utils/ligolw_sqlite.py -> build/lib.macosx-10.15-x86_64-cpython-38/ligo/lw/utils
>       copying ligo/lw/utils/coincs.py -> build/lib.macosx-10.15-x86_64-cpython-38/ligo/lw/utils
>       copying ligo/lw/utils/process.py -> build/lib.macosx-10.15-x86_64-cpython-38/ligo/lw/utils
>       copying ligo/lw/utils/time_slide.py -> build/lib.macosx-10.15-x86_64-cpython-38/ligo/lw/utils
>       running build_ext
>       building 'ligo.lw.tokenizer' extension
>       creating build/temp.macosx-10.15-x86_64-cpython-38
>       creating build/temp.macosx-10.15-x86_64-cpython-38/ligo
>       creating build/temp.macosx-10.15-x86_64-cpython-38/ligo/lw
>       clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -Iligo/lw -I/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/include/python3.8 -c ligo/lw/tokenizer.RowBuilder.c -o build/temp.macosx-10.15-x86_64-cpython-38/ligo/lw/tokenizer.RowBuilder.o
>       xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
>       error: command '/usr/bin/clang' failed with exit code 1
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for python-ligo-lw
>   Running setup.py clean for python-ligo-lw
>   Building wheel for lscsoft-glue (pyproject.toml) ... error
>   error: subprocess-exited-with-error
>   
>   × Building wheel for lscsoft-glue (pyproject.toml) did not run successfully.
>   │ exit code: 1
>   ╰─> [55 lines of output]
>       running bdist_wheel
>       running build
>       running build_py
>       generating glue/git_version.py
>       /private/var/folders/s9/t49rydtj00dfkh3ps3s2lgg40000gn/T/pip-build-env-2p3j3xhe/overlay/lib/python3.8/site-packages/setuptools/config/setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
>         warnings.warn(msg, warning_class)
>       not in git checkout or cannot find git executable; using existing glue/git_version.py
>       creating build
>       creating build/lib.macosx-10.15-x86_64-cpython-38
>       creating build/lib.macosx-10.15-x86_64-cpython-38/glue
>       copying glue/text_progress_bar.py -> build/lib.macosx-10.15-x86_64-cpython-38/glue
>       copying glue/pidfile.py -> build/lib.macosx-10.15-x86_64-cpython-38/glue
>       copying glue/LDBDWClient.py -> build/lib.macosx-10.15-x86_64-cpython-38/glue
>       copying glue/iterutils.py -> build/lib.macosx-10.15-x86_64-cpython-38/glue
>       copying glue/gpstime.py -> build/lib.macosx-10.15-x86_64-cpython-38/glue
>       copying glue/__init__.py -> build/lib.macosx-10.15-x86_64-cpython-38/glue
>       copying glue/markup.py -> build/lib.macosx-10.15-x86_64-cpython-38/glue
>       copying glue/utils.py -> build/lib.macosx-10.15-x86_64-cpython-38/glue
>       copying glue/pipeline.py -> build/lib.macosx-10.15-x86_64-cpython-38/glue
>       copying glue/lal.py -> build/lib.macosx-10.15-x86_64-cpython-38/glue
>       copying glue/git_version.py -> build/lib.macosx-10.15-x86_64-cpython-38/glue
>       copying glue/ldbd.py -> build/lib.macosx-10.15-x86_64-cpython-38/glue
>       creating build/lib.macosx-10.15-x86_64-cpython-38/glue/ligolw
>       copying glue/ligolw/ligolw.py -> build/lib.macosx-10.15-x86_64-cpython-38/glue/ligolw
>       copying glue/ligolw/ilwd.py -> build/lib.macosx-10.15-x86_64-cpython-38/glue/ligolw
>       copying glue/ligolw/lsctables.py -> build/lib.macosx-10.15-x86_64-cpython-38/glue/ligolw
>       copying glue/ligolw/__init__.py -> build/lib.macosx-10.15-x86_64-cpython-38/glue/ligolw
>       copying glue/ligolw/param.py -> build/lib.macosx-10.15-x86_64-cpython-38/glue/ligolw
>       copying glue/ligolw/types.py -> build/lib.macosx-10.15-x86_64-cpython-38/glue/ligolw
>       copying glue/ligolw/dbtables.py -> build/lib.macosx-10.15-x86_64-cpython-38/glue/ligolw
>       copying glue/ligolw/table.py -> build/lib.macosx-10.15-x86_64-cpython-38/glue/ligolw
>       copying glue/ligolw/array.py -> build/lib.macosx-10.15-x86_64-cpython-38/glue/ligolw
>       creating build/lib.macosx-10.15-x86_64-cpython-38/glue/segmentdb
>       copying glue/segmentdb/query_engine.py -> build/lib.macosx-10.15-x86_64-cpython-38/glue/segmentdb
>       copying glue/segmentdb/segmentdb_utils.py -> build/lib.macosx-10.15-x86_64-cpython-38/glue/segmentdb
>       copying glue/segmentdb/__init__.py -> build/lib.macosx-10.15-x86_64-cpython-38/glue/segmentdb
>       creating build/lib.macosx-10.15-x86_64-cpython-38/glue/ligolw/utils
>       copying glue/ligolw/utils/coalesce_db.py -> build/lib.macosx-10.15-x86_64-cpython-38/glue/ligolw/utils
>       copying glue/ligolw/utils/ligolw_add.py -> build/lib.macosx-10.15-x86_64-cpython-38/glue/ligolw/utils
>       copying glue/ligolw/utils/search_summary.py -> build/lib.macosx-10.15-x86_64-cpython-38/glue/ligolw/utils
>       copying glue/ligolw/utils/segments.py -> build/lib.macosx-10.15-x86_64-cpython-38/glue/ligolw/utils
>       copying glue/ligolw/utils/__init__.py -> build/lib.macosx-10.15-x86_64-cpython-38/glue/ligolw/utils
>       copying glue/ligolw/utils/ligolw_sqlite.py -> build/lib.macosx-10.15-x86_64-cpython-38/glue/ligolw/utils
>       copying glue/ligolw/utils/coincs.py -> build/lib.macosx-10.15-x86_64-cpython-38/glue/ligolw/utils
>       copying glue/ligolw/utils/print_tables.py -> build/lib.macosx-10.15-x86_64-cpython-38/glue/ligolw/utils
>       copying glue/ligolw/utils/process.py -> build/lib.macosx-10.15-x86_64-cpython-38/glue/ligolw/utils
>       copying glue/ligolw/utils/time_slide.py -> build/lib.macosx-10.15-x86_64-cpython-38/glue/ligolw/utils
>       running build_ext
>       building 'glue.ligolw.tokenizer' extension
>       creating build/temp.macosx-10.15-x86_64-cpython-38
>       creating build/temp.macosx-10.15-x86_64-cpython-38/glue
>       creating build/temp.macosx-10.15-x86_64-cpython-38/glue/ligolw
>       clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -Isrc -Iglue/ligolw -I/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/include/python3.8 -c glue/ligolw/tokenizer.RowBuilder.c -o build/temp.macosx-10.15-x86_64-cpython-38/glue/ligolw/tokenizer.RowBuilder.o
>       xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
>       error: command '/usr/bin/clang' failed with exit code 1
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for lscsoft-glue
> Failed to build ligo-segments python-ligo-lw lscsoft-glue
> ERROR: Could not build wheels for lscsoft-glue, which is required to install pyproject.toml-based projects

**Comment by lpsinger** [comment]
Please make sure that you have the latest version of Xcode installed, and that you have installed Xcode's command line tools.
