### ISSUE TITLE
Inconsistent tuple lengths in find_ellipse

### ISSUE THREAD

**Issue by bpiotrzkowski** [lpsinger/ligo.skymap#17]
When testing in gwcelery, an error was found in `find_ellipse` where the expected values to unpack were different from expected
![Screen Shot 2022-10-06 at 10 35 13 AM](https://user-images.githubusercontent.com/37160952/194341659-462d6667-3398-4aca-b60b-9e9ddbe65c90.png)

This appears to occur due to the tuples returned being different lengths, with the standard output being six values https://github.com/lpsinger/ligo.skymap/blob/ba63039d857d5097417e5d967d7d6db185327d5f/ligo/skymap/postprocess/ellipse.py#L387 and the error output being five https://github.com/lpsinger/ligo.skymap/blob/ba63039d857d5097417e5d967d7d6db185327d5f/ligo/skymap/postprocess/ellipse.py#L371
This could be fixed by changing the latter output to six np.nan values.

**Comment by lpsinger** [comment]
Would you please report this at https://git.ligo.org/lscsoft/ligo.skymap/-/issues/new?
