### ISSUE TITLE
Issue with running the Script for ligo_skymap_plot_volume.py

### ISSUE THREAD

**Issue by choudharyharsh122** [lpsinger/ligo.skymap#18]
how do I run the script for ligo_skymap_plot_volume.py , everytime I do this, i run into some problem with relative imports.

**Comment by lpsinger** [comment]
Please supply some more detail.

**Comment by choudharyharsh122** [comment]
I cloned your repo and I am trying to plot the projections along the 3 directions.

This is how I am trying to run the script:  
! python ligo/skymap/tool/ligo_skymap_plot_volume.py -annotate 'False' -max_distance '100' -contour '90' -projection '0' -input 'https://emfollow.docs.ligo.org/userguide/_static/bayestar.fits.gz'

I am getting the following error: 
Traceback (most recent call last):
  File "/home/harsh/ligo.skymap/ligo/skymap/tool/ligo_skymap_plot_volume.py", line 20, in <module>
    from . import ArgumentParser, FileType
ImportError: attempted relative import with no known parent package

**Comment by choudharyharsh122** [comment]
I wanted to know is this the right way, because I couldn't find any thorough documentation on this

**Comment by lpsinger** [comment]
You don't need to clone this repository to use ligo.skymap. Just follow the installation instructions here:
https://lscsoft.docs.ligo.org/ligo.skymap/quickstart/install.html

**Comment by lpsinger** [comment]
Is this working for you now?

**Comment by choudharyharsh122** [comment]
Hi @lpsinger , yes it's working for me now, many thanks.
I wanted to make some modifications in the distance plot
