### ISSUE TITLE
Issue with Coordinate Transform in Inset

### ISSUE THREAD

**Issue by rhsharpe** [lpsinger/ligo.skymap#23]
Hi!

I am trying to display a fits skymap within an inset on a contour plot (similar to what is shown here: https://lscsoft.docs.ligo.org/ligo.skymap/ but with just the Gemini+F2 plot in the inset). I am having trouble getting the coordinate transforms within the inset to work properly. 

If I don't include a transform within the ax_inset.imshow() command, it appears to only show a small corner of the skymap in the inset, which makes sense.

If I use the same transform I used for the skymap plotted in the larger figure (from the header of the fits file) within the ax_inset.imshow() command, the inset is completely blank.

The only way I can get any data to appear in the inset is to use ax.get_transform('pixel'), but then I have the issue of the scale being off. 

I've attached examples of the three situations I mentioned. Do you have any suggestions for plotting a fits image, with the correct scaling, as an inset of a healpix contour plot? 
![no_transform](https://github.com/lpsinger/ligo.skymap/assets/86579381/ee204b63-2677-485d-b197-ea9ae6392ef3)
![header_transform](https://github.com/lpsinger/ligo.skymap/assets/86579381/9e9abc8d-7623-4d98-aa5a-eb6abda0ca83)
![pixel_transform](https://github.com/lpsinger/ligo.skymap/assets/86579381/8254ae0b-f8f4-467a-995e-f0b109c4a9b9)

**Comment by lpsinger** [comment]
Would you please share your code?

**Comment by rhsharpe** [comment]
Yes, here is a zip file with my python notebook and the two files I am plotting:
[skymap.zip](https://github.com/lpsinger/ligo.skymap/files/12370008/skymap.zip)

**Comment by lpsinger** [comment]
Oh, I see. You have to reproject the image data for the zoomed in axes. I suggest using https://reproject.readthedocs.io/en/stable/.
