### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by ferrigno** [lpsinger/ligo.skymap#8]
Hi

it would be very helpful for a user like me  to see an example on how to build the beautiful plot at https://lscsoft.docs.ligo.org/ligo.skymap/
At least the part with the localisation map projected on the sphere with the GBM and IPN localisations.

Would you link a github repository with the source code of some plots?

Many thanks,
Carlo

**Comment by ferrigno** [comment]
I found an example in the code, but it is not working. I hope another issue.

**Comment by lpsinger** [comment]
Most of the features in that plot are present in the code samples from this manual page: https://lscsoft.docs.ligo.org/ligo.skymap/plot/allsky.html

**Comment by ferrigno** [comment]
Managed at the end, thanks.
